### ISSUE TITLE
Link to latest GSoC Guide

### ISSUE THREAD

**Issue by xypnox** [OrkoHunter/gsoc-FAQs#11]
## What is your query? 

The GSoC Guide link mentioned has been shifted to : https://google.github.io/gsocguides/student/

## Is this question specific to a participating organization?
No

## Have you read the [FLOSS Manual](http://write.flossmanuals.net/gsocstudentguide) yet?

Yep, but The docs have moved.

## Have you read the questions in the [README](https://github.com/OrkoHunter/gsoc-FAQs/blob/master/README.md)?

Yeps

## Did you Google search this before posting?

Hell yeah

## Do you think this question will help other applicants?

This is not a question

**Comment by OrkoHunter** [comment]
Thanks! ✨
