### ISSUE TITLE
Organization Selection

### ISSUE THREAD

**Issue by ShyamPraveenSingh** [OrkoHunter/gsoc-FAQs#13]
NOTE:
 - Have you read [How to Ask Questions the Smart Way](http://www.catb.org/esr/faqs/smart-questions.html) ?
 - Please fill out the template below to get a definite answer.

## What is your query? 

> Although it is not possible to predict which organisation is going to get selected, but can you add the list of organisation that gets accepted  regularly

## Is this question specific to a participating organization?

> N

## Have you read the [FLOSS Manual](http://write.flossmanuals.net/gsocstudentguide) yet?

> Y

## Have you read the questions in the [README](https://github.com/OrkoHunter/gsoc-FAQs/blob/master/README.md)?

> Y

## Did you Google search this before posting?

> Y

## Do you think this question will help other applicants?

> Y

**Comment by thealphadollar** [comment]
Hey Shyam, thank you for the request and creating an issue. I'm sure if we could create such a list, it would have been highly useful to all students preparing and remove a major part of the confusion.

I'm just worried that it might not be feasible to create such a list as selected organizations keep changing every year with new format and rules of GSoC. The best way, IMO, is for students to explore the organizations from GSoC archives. If we put up a list of organizations - students will consider it as a final list of organizations (as there's always a lot of confusion and students miss reading the manuals) and then we would be held liable if some organization is not selected.

Leaving all that, the process of going through archives gives a student a holistic information about organizations that get selected and it helps them to build up a decision. Definitely, and I understand as I've been a student, the process is time consuming and we wish there was a list which could tell us everything there is. However, don't you think removing that process and giving a list out-rightly will skip an important learning step?

Do you think a better question would be "How should I select an organization"? Google's student guide already has a precise answer to this [here](https://google.github.io/gsocguides/student/choosing-an-organization).

PS. @OrkoHunter is the BDFL for the repository and his decision would be final, above is only my personal opinion.

**Comment by ShyamPraveenSingh** [comment]
Hi @thealphadollar, Thanks for responding.

I totally agree with all the points you have mentioned and yes going through the archives is the best approach for selecting an organization. 

However, I was planning to start preparing for GSOC by selecting  an organization early and learning about the tech stacks used in their organization. And I think going through the archives and selecting 3-4 organizations to contribute seems to be the best way to do it, while hoping for the same organization to get selected again.


On the side note,  is it possible to add the number of times a particular organization has been selected in GSOC.
I guess this would provide a great insight for students and it would atleast give them an idea about the popular organizations.

**Comment by OrkoHunter** [comment]
> On the side note, is it possible to add the number of times a particular organization has been selected in GSOC.
I guess this would provide a great insight for students and it would atleast give them an idea about the popular organizations.

You are mostly likely to find this information on the organizations' wiki where they put their idea proposals. Plus, you can see this in GSoC archives as well.

@thealphadollar I very much appreciate you sharing your opinions here. They are more fresh and valuable to the community. :)
